---  # to run ungrouped servers
all:
  hosts:
  children:
    dev:
      hosts:
        web1:
          ansible_host: 10.124.0.3
          ansible_port: 22
        web2:
          ansible_host: 10.124.0.4
          ansible_port: 7789